# Generated by Django 4.2.9 on 2024-02-08 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 8, 9, 27, 12, 278815, tzinfo=datetime.timezone.utc)),
        ),
    ]
