# Generated by Django 4.2.9 on 2024-02-08 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_publish_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 8, 10, 3, 39, 156204, tzinfo=datetime.timezone.utc)),
        ),
    ]
