# Generated by Django 4.2.9 on 2024-02-09 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 9, 16, 52, 55, 450669, tzinfo=datetime.timezone.utc)),
        ),
    ]
