# Generated by Django 4.2.9 on 2024-02-13 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_img_alter_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 13, 9, 53, 10, 608996, tzinfo=datetime.timezone.utc)),
        ),
    ]
