# Generated by Django 4.2.9 on 2024-02-16 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_publish_like_comment_post_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 16, 15, 36, 35, 828001, tzinfo=datetime.timezone.utc)),
        ),
    ]
